// apps/hello-world-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import mondaySdk from "monday-sdk-js";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  monday;
  user;
  settings;
  context;

  constructor() {
    this.monday = mondaySdk();
    this.settings = "";
    this.context = "";
    this.user = "";
  }

  ngOnInit() {
    this.fetchUserName();
    var self = this;
    this.monday.listen("settings", res => self.getSettings(res));
    this.monday.listen("context", res => self.getContext(res));
  }

  fetchUserName() {
    this.monday.api(`query { me { name } }`).then(res => {
      this.user = res.data.me;
    });
  }

  getSettings(res) {
    this.settings = JSON.stringify(res.data);
  }

  getContext(res) {
    this.context = JSON.stringify(res.data);
  }
}

<div>Hello {{ user.name }}!</div>
<div>Your context: {{ context }}</div>
<div>Your settings: {{ settings }}</div>

// apps/hello-world-react/src/App.js
import React from "react";
import mondaySdk from "monday-sdk-js";
const monday = mondaySdk();

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { settings: {}, context: {}, userName: "monday" };
  }

  componentDidMount() {
    monday.listen("settings", this.getSettings);
    monday.listen("context", this.getContext);
    monday.api(`query { me { name } }`).then(this.getUser)
  }

  getSettings = res => {
    this.setState({ settings: res.data });
  };

  getContext = res => {
    this.setState({ context: res.data });
  };

  getUser = res => {
    this.setState({ userName: res.data.me.name });
  };

  render() {
    const { settings, context, userName } = this.state;

    return (
      <div className="monday-app">
        <div>Hello {userName}!</div>
        <div>Your context: {JSON.stringify(context)}</div>
        <div>Your settings: {JSON.stringify(settings)}</div>
      </div>
    );
  }
}

export default App;
