// apps/hello-world-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import mondaySdk from "monday-sdk-js";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  monday;
  user;
  settings;
  context;

  constructor() {
    this.monday = mondaySdk();
    this.settings = "";
    this.context = "";
    this.user = "";
  }

  ngOnInit() {
    this.fetchUserName();
    var self = this;
    this.monday.listen("settings", res => self.getSettings(res));
    this.monday.listen("context", res => self.getContext(res));
  }

  fetchUserName() {
    this.monday.api(`query { me { name } }`).then(res => {
      this.user = res.data.me;
    });
  }

  getSettings(res) {
    this.settings = JSON.stringify(res.data);
  }

  getContext(res) {
    this.context = JSON.stringify(res.data);
  }
}

<div>Hello {{ user.name }}!</div>
<div>Your context: {{ context }}</div>
<div>Your settings: {{ settings }}</div>

// apps/hello-world-vuejs/src/App.vue
<template>
  <div id="app">
    <div>Hello {{ user.name }}</div>
    <div>Your context: {{ JSON.stringify(context) }}</div>
    <div>Your settings: {{ JSON.stringify(settings) }}</div>
  </div>
</template>

<script>
import mondaySdk from "monday-sdk-js";
const monday = mondaySdk();

export default {
  name: "app",
  data() {
    return {
      settings: "",
      context: "",
      user: ""
    };
  },

  mounted() {
    monday.listen("settings", this.getSettings);
    monday.listen("context", this.getContext);
    this.fetchUserName();
  },

  methods: {
    beforeCreate() {
      this.fetchUserName();
    },

    getSettings: function(res) {
      this.$set(this, "settings", res.data);
    },

    getContext: function(res) {
      this.$set(this, "context", res.data);
    },

    fetchUserName: function() {
      monday.api(`query { me { name } }`).then(res => {
        this.$set(this, "user", res.data.me);
      });
    }
  }
};
</script>

<style lang="scss">
#app {
  text-align: center;
  margin-top: 60px;
}
</style>
